"""Placeholder POI data scattered around Prasanthi Nilayam, Puttaparthi.

Coordinates are approximate and for prototyping only — replace with
surveyed points once real data is available. Seeded into the database
once; after that, edit records via the /admin panel instead of here.
"""

SEED_POIS: list[dict] = [
    dict(
        id="mandir-skh",
        name="Sai Kulwant Hall",
        category="mandir",
        lat=14.1666,
        lon=77.8033,
        description="Main darshan hall. Footwear counter at the north entrance.",
        search_terms="darshan, mandir, temple, bhajan hall, sannidhi",
        opening_hours="Darshan 6:30 AM & 4:00 PM",
        accessible=True,
        maintained_by="Trust",
    ),
    dict(
        id="water-gate3",
        name="Drinking Water — Gate 3",
        category="water_restrooms",
        lat=14.1671,
        lon=77.8027,
        description="RO water point, refill bottles here.",
        search_terms="kiosk, water kiosk, RO water, tap, drinking water, bottle refill",
        opening_hours="Open 24 hours",
        accessible=True,
    ),
    dict(
        id="water-canteen",
        name="Drinking Water — Canteen Block",
        category="water_restrooms",
        lat=14.1660,
        lon=77.8041,
        search_terms="kiosk, water kiosk, RO water, tap, drinking water, bottle refill",
        opening_hours="Open 24 hours",
        accessible=True,
    ),
    dict(
        id="restroom-block4-ladies",
        name="Restroom — Block 4 (Ladies)",
        category="water_restrooms",
        lat=14.1674,
        lon=77.8038,
        gender="ladies",
        search_terms="toilet, loo, washroom, WC, ladies room",
        opening_hours="5:00 AM – 10:00 PM",
        accessible=True,
        maintained_by="Seva Dal",
    ),
    dict(
        id="restroom-block4-gents",
        name="Restroom — Block 4 (Gents)",
        category="water_restrooms",
        lat=14.1675,
        lon=77.8039,
        gender="gents",
        search_terms="toilet, loo, washroom, WC, gents room, mens room",
        opening_hours="5:00 AM – 10:00 PM",
        maintained_by="Seva Dal",
    ),
    dict(
        id="stay-block4",
        name="Accommodation — Block 4",
        category="accommodation",
        lat=14.1677,
        lon=77.8036,
        search_terms="room, guest house, lodging, stay, dorm",
        capacity_note="Rooms available",
        opening_hours="Check-in 12:00 PM · Check-out 9:00 AM",
    ),
    dict(
        id="stay-block9",
        name="Accommodation — Block 9",
        category="accommodation",
        lat=14.1648,
        lon=77.8019,
        search_terms="room, guest house, lodging, stay, dorm",
        capacity_note="Full",
        opening_hours="Check-in 12:00 PM · Check-out 9:00 AM",
        accessible=True,
    ),
    dict(
        id="prasadam-canteen",
        name="Prasadam Canteen",
        category="canteens_shopping",
        lat=14.1659,
        lon=77.8043,
        search_terms="food, meals, dining, breakfast, lunch, dinner, canteen, refreshments",
        opening_hours="Breakfast 7–9 AM · Lunch 12–2 PM · Dinner 7–9 PM",
        accessible=True,
        maintained_by="Seva Dal",
    ),
    dict(
        id="spiritual-poornachandra",
        name="Poornachandra Auditorium",
        category="spiritual_places",
        lat=14.1663,
        lon=77.8029,
        description="Auditorium for programs and gatherings.",
        search_terms="auditorium, hall, program venue, event hall",
        accessible=True,
    ),
    dict(
        id="library-book-trust",
        name="Sri Sathya Sai Book Trust — Library & Book Stall",
        category="library",
        lat=14.1656,
        lon=77.8036,
        search_terms="books, book stall, reading room, publications",
        opening_hours="9:00 AM – 12:00 PM · 3:00 PM – 6:00 PM",
        accessible=True,
        maintained_by="Trust",
    ),
    dict(
        id="help-desk-office",
        name="Seva Dal Help Desk — Ashram Office",
        category="offices",
        lat=14.1652,
        lon=77.8022,
        description="PRO, Central Trust, Sadhana Trust, Police Station enquiries. Also lost & found and wheelchair loans.",
        search_terms="PRO, central trust, sadhana trust, police station, office, enquiry, lost and found, wheelchair",
        opening_hours="6:00 AM – 8:00 PM",
        accessible=True,
        maintained_by="Seva Dal",
    ),
]
